CREATE TABLE USERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    age INT,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);