spring:
  application:
    name: PixView
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: org.h2.Driver
    username: pixviewadm
    password: pixviewadm
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true
server:
  port: '8082'